### ISSUE TITLE
crashed in my MI4 phone

### ISSUE THREAD

**Issue by xiaohuzi9527** [pedrovgs/EffectiveAndroidUI#16]
the crash log:
01-15 11:57:23.631 11565-11565/? D/dalvikvm: Late-enabling CheckJNI
01-15 11:57:23.701 11565-11565/com.github.pedrovgs.effectiveandroidui W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
01-15 11:57:23.701 11565-11565/com.github.pedrovgs.effectiveandroidui I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onSearchRequested
01-15 11:57:23.701 11565-11565/com.github.pedrovgs.effectiveandroidui W/dalvikvm: VFY: unable to resolve interface method 14134: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
01-15 11:57:23.701 11565-11565/com.github.pedrovgs.effectiveandroidui D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-15 11:57:23.701 11565-11565/com.github.pedrovgs.effectiveandroidui I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onWindowStartingActionMode
01-15 11:57:23.701 11565-11565/com.github.pedrovgs.effectiveandroidui W/dalvikvm: VFY: unable to resolve interface method 14138: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
01-15 11:57:23.701 11565-11565/com.github.pedrovgs.effectiveandroidui D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-15 11:57:23.741 11565-11565/com.github.pedrovgs.effectiveandroidui I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
01-15 11:57:23.741 11565-11565/com.github.pedrovgs.effectiveandroidui W/dalvikvm: VFY: unable to resolve virtual method 421: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
01-15 11:57:23.741 11565-11565/com.github.pedrovgs.effectiveandroidui D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
01-15 11:57:23.741 11565-11565/com.github.pedrovgs.effectiveandroidui I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
01-15 11:57:23.741 11565-11565/com.github.pedrovgs.effectiveandroidui W/dalvikvm: VFY: unable to resolve virtual method 443: Landroid/content/res/TypedArray;.getType (I)I
01-15 11:57:23.741 11565-11565/com.github.pedrovgs.effectiveandroidui D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
01-15 11:57:23.801 11565-11565/com.github.pedrovgs.effectiveandroidui D/dalvikvm: GC_FOR_ALLOC freed 395K, 26% free 23039K/30732K, paused 15ms, total 15ms
01-15 11:57:23.811 11565-11565/com.github.pedrovgs.effectiveandroidui I/dalvikvm-heap: Grow heap (frag case) to 39.105MB for 9000016-byte allocation
01-15 11:57:23.871 11565-11565/com.github.pedrovgs.effectiveandroidui I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: YWEN_+PATCH[ES]_msm8974_refs/tags/AU_LINUX_ANDROID_LNX.LA.3.5.2.2.1_RB1.04.04.04.090.059__release_ENGG ()
                                                                                    OpenGL ES Shader Compiler Version: E031.24.00.15
                                                                                    Build Date: 11/04/15 Wed
                                                                                    Local Branch: tip
                                                                                    Remote Branch: quic/kk_3.5_1
                                                                                    Local Patches: 14b1eae272f4a5ed345b2294a1c76becd9b27371 rb: re-work change "ES2.0 Fix for shadow cached VBO validation"
                                                                                                     c63208cf6c1fe92a04d7ed7e26be44f2f51c94e9 Revert "Fix for perf regression from "ES2.0 Fix for shadow cached VBO validation""
01-15 11:57:23.901 11565-11565/com.github.pedrovgs.effectiveandroidui D/OpenGLRenderer: Enabling debug mode 0
01-15 11:57:23.981 11565-11565/com.github.pedrovgs.effectiveandroidui I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@42d5f680 time:180624621
01-15 11:57:25.371 11565-11565/com.github.pedrovgs.effectiveandroidui D/AndroidRuntime: Shutting down VM
01-15 11:57:25.371 11565-11565/com.github.pedrovgs.effectiveandroidui W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41755d58)
01-15 11:57:25.421 11565-11565/com.github.pedrovgs.effectiveandroidui E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.github.pedrovgs.effectiveandroidui, PID: 11565
                                                                                        android.view.InflateException: Binary XML file line #11: Error inflating class android.widget.TextView
                                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                                            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                                            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
                                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                                            at com.github.pedrovgs.effectiveandroidui.ui.renderer.tvshow.TvShowRenderer.inflate(TvShowRenderer.java:66)
                                                                                            at com.pedrogomez.renderers.Renderer.onCreate(Renderer.java:52)
                                                                                            at com.pedrogomez.renderers.RendererBuilder.createRenderer(RendererBuilder.java:143)
                                                                                            at com.pedrogomez.renderers.RendererBuilder.build(RendererBuilder.java:115)
                                                                                            at com.pedrogomez.renderers.RendererAdapter.getView(RendererAdapter.java:89)
                                                                                            at android.widget.AbsListView.obtainView(AbsListView.java:2257)
                                                                                            at android.widget.GridView.onMeasure(GridView.java:1044)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                                            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                            at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                                            at android.view.View.measure(View.java:16529)
                                                                                            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1973)
                                                                                            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1170)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1352)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1057)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5666)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                        	at com.android.internal.os.ZygoteInit.main(ZygoteI
01-15 11:57:27.361 11565-11565/com.github.pedrovgs.effectiveandroidui I/Process: Sending signal. PID: 11565 SIG: 9

**Comment by forever4313** [comment]
I think this caused by style attribute

**Comment by pedrovgs** [comment]
Related to #17 can someone with the fix send a PR?

**Comment by haogg** [comment]
混淆吧
