### ISSUE TITLE
Crashing in samsung galaxy note 3 v4.3

### ISSUE THREAD

**Issue by gjnidea** [pedrovgs/EffectiveAndroidUI#17]
Part of error report:

    FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #11: Error inflating class android.widget.TextView
        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                                            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                                            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
                                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                            at com.github.pedrovgs.effectiveandroidui.ui.renderer.tvshow.TvShowRenderer.inflate(TvShowRenderer.java:66)

Inflation error occurs in `TvShowRenderer` line `66` when inflating `R.layout.row_tv_show`

**Comment by optcheng** [comment]
I meet this problem,too
And you can see issue #16 . forever4313 gave a solution. It works for me.

I changed `row_tv_show.xml` like this:
```xml
  <ImageView
      android:id="@+id/iv_thumbnail"
      android:layout_width="match_parent"
      android:layout_height="@dimen/poster_height"
      android:layout_alignParentTop="true"/>

  <TextView
      android:id="@+id/tv_title"
      android:layout_below="@+id/iv_thumbnail"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:ellipsize="end"
      android:singleLine="true"
      android:layout_marginLeft="@dimen/secondary_margin"/>

  <TextView
      android:id="@+id/tv_seasons_counter"
      android:layout_below="@+id/tv_title"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:ellipsize="end"
      android:singleLine="true"
      android:layout_marginLeft="@dimen/secondary_margin"
      android:paddingBottom="@dimen/main_margin"/>
```

Then l meet another XML file error later.
I also changed the style to related attributes,it works well,too.

**Comment by pedrovgs** [comment]
Sorry for the delay, I've been out for some time. Can you send a PR with the fix?
