### ISSUE TITLE
Crashed in Smartisan T1

### ISSUE THREAD

**Issue by wanyt** [pedrovgs/EffectiveAndroidUI#23]
when i click item in the main view, it crashed. this is the error:

26643-26643/com.github.pedrovgs.effectiveandroidui E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.github.pedrovgs.effectiveandroidui, PID: 26643
                                                                                        android.view.InflateException: Binary XML file line #7: Error inflating class <unknown>
                                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                                            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                                            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                            at com.github.pedrovgs.effectiveandroidui.ui.renderer.chapter.ChapterRenderer.inflate(ChapterRenderer.java:61)
                                                                                            at com.pedrogomez.renderers.Renderer.onCreate(Renderer.java:52)
                                                                                            at com.pedrogomez.renderers.RendererBuilder.createRenderer(RendererBuilder.java:143)
                                                                                            at com.pedrogomez.renderers.RendererBuilder.build(RendererBuilder.java:115)
                                                                                            at com.pedrogomez.renderers.RendererAdapter.getView(RendererAdapter.java:89)
                                                                                            at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
                                                                                            at android.widget.AbsListView.obtainView(AbsListView.java:2377)
                                                                                            at android.widget.ListView.makeAndAddView(ListView.java:1792)
                                                                                            at android.widget.ListView.fillDown(ListView.java:693)
                                                                                            at android.widget.ListView.fillFromTop(ListView.java:754)
                                                                                            at android.widget.ListView.layoutChildren(ListView.java:1632)
                                                                                            at android.widget.AbsListView.onLayout(AbsListView.java:2202)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at com.github.pedrovgs.DraggableView.onLayout(DraggableView.java:433)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2966)
                                                                                            at android.view.View.layout(View.java:14845)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2070)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1810)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5790)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:5

Error occurred in the line 61 of the ChapterRenderer.class, this is the code:
`@Override protected View inflate(LayoutInflater layoutInflater, ViewGroup viewGroup) {
    return layoutInflater.inflate(R.layout.row_chapter, viewGroup, false);
  }`

i don't know why such a error occurred.

**Comment by pedrovgs** [comment]
Hi @wanyt trying to reproduce the crash I couldn't get how to crash the app. If you could reproduce it and send a pull request with the fix that'd be great. If you don't have time, please send me a list of steps to reproduce the bug so I can figure out how to fix it. Thanks!
